server:
  port: 8888
  forward-headers-strategy: native

spring:
  application:
    name: task-service
  data:
    web:
      hateoas:
        use-hal-as-default-json-media-type: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
